import Link from 'next/link';
import { getPostBySlug } from '@/lib/fsPosts';
import { renderMarkdown } from '@/lib/markdown';
import { notFound } from 'next/navigation';
import DeleteButton from '@/components/DeleteButton';
import BackToGenerator from '@/components/BackToGenerator';

export default async function BlogPostPage({
  params,
}: {
  params: { slug: string };
}) {
  const post = await getPostBySlug(params.slug);

  if (!post) {
    notFound();
  }

  const html = await renderMarkdown(post.body);
  const date = new Date(post.meta.createdAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return (
    <div className="min-h-screen flex flex-col">
      <nav className="backdrop-blur-md bg-white/5 border-b border-white/10">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex justify-between items-center">
            <Link
              href="/blog"
              className="text-white/90 hover:text-white font-medium transition-colors px-4 py-2 rounded-lg hover:bg-white/10"
            >
              ← Back to Blog
            </Link>
            <div className="flex items-center gap-3">
              <BackToGenerator />
              <DeleteButton slug={post.meta.slug} redirect="/blog" />
            </div>
          </div>
        </div>
      </nav>

      <article className="flex-1 prose prose-lg max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div
          dangerouslySetInnerHTML={{ __html: html }}
          className="backdrop-blur-xl bg-white/10 rounded-xl shadow-2xl border border-white/20 p-8 mb-8 text-white prose-headings:text-white prose-p:text-white/90 prose-strong:text-white prose-code:text-purple-200 prose-pre:bg-black/30 prose-a:text-purple-300"
        />

        <footer className="backdrop-blur-xl bg-white/10 rounded-xl shadow-2xl border border-white/20 p-6">
          <div className="flex items-center justify-between text-sm text-white/80">
            <div>
              <span className="font-medium">Generated by:</span> {post.meta.provider}
            </div>
            <div>
              <span className="font-medium">Created:</span> {date}
            </div>
          </div>
        </footer>
      </article>
    </div>
  );
}

